version: '3'

services:
  site:
    image: RateThing
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - "50000:50000"
      - "50001:50001"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - Google__ClientId
      - Google__ClientSecret

    volumes:
      - ./:/app/
  
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: topsecret
    ports:
      - "50002:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5
    ports:
      - "50003:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
